require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ApplistsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Applist. As you add validations to Applist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ApplistsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all applists as @applists" do
      applist = Applist.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:applists)).to eq([applist])
    end
  end

  describe "GET #show" do
    it "assigns the requested applist as @applist" do
      applist = Applist.create! valid_attributes
      get :show, params: {id: applist.to_param}, session: valid_session
      expect(assigns(:applist)).to eq(applist)
    end
  end

  describe "GET #new" do
    it "assigns a new applist as @applist" do
      get :new, params: {}, session: valid_session
      expect(assigns(:applist)).to be_a_new(Applist)
    end
  end

  describe "GET #edit" do
    it "assigns the requested applist as @applist" do
      applist = Applist.create! valid_attributes
      get :edit, params: {id: applist.to_param}, session: valid_session
      expect(assigns(:applist)).to eq(applist)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Applist" do
        expect {
          post :create, params: {applist: valid_attributes}, session: valid_session
        }.to change(Applist, :count).by(1)
      end

      it "assigns a newly created applist as @applist" do
        post :create, params: {applist: valid_attributes}, session: valid_session
        expect(assigns(:applist)).to be_a(Applist)
        expect(assigns(:applist)).to be_persisted
      end

      it "redirects to the created applist" do
        post :create, params: {applist: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Applist.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved applist as @applist" do
        post :create, params: {applist: invalid_attributes}, session: valid_session
        expect(assigns(:applist)).to be_a_new(Applist)
      end

      it "re-renders the 'new' template" do
        post :create, params: {applist: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested applist" do
        applist = Applist.create! valid_attributes
        put :update, params: {id: applist.to_param, applist: new_attributes}, session: valid_session
        applist.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested applist as @applist" do
        applist = Applist.create! valid_attributes
        put :update, params: {id: applist.to_param, applist: valid_attributes}, session: valid_session
        expect(assigns(:applist)).to eq(applist)
      end

      it "redirects to the applist" do
        applist = Applist.create! valid_attributes
        put :update, params: {id: applist.to_param, applist: valid_attributes}, session: valid_session
        expect(response).to redirect_to(applist)
      end
    end

    context "with invalid params" do
      it "assigns the applist as @applist" do
        applist = Applist.create! valid_attributes
        put :update, params: {id: applist.to_param, applist: invalid_attributes}, session: valid_session
        expect(assigns(:applist)).to eq(applist)
      end

      it "re-renders the 'edit' template" do
        applist = Applist.create! valid_attributes
        put :update, params: {id: applist.to_param, applist: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested applist" do
      applist = Applist.create! valid_attributes
      expect {
        delete :destroy, params: {id: applist.to_param}, session: valid_session
      }.to change(Applist, :count).by(-1)
    end

    it "redirects to the applists list" do
      applist = Applist.create! valid_attributes
      delete :destroy, params: {id: applist.to_param}, session: valid_session
      expect(response).to redirect_to(applists_url)
    end
  end

end
